BU菜单: "xpath==//div[@class='main-top-audit']//div[contains(text(),'variable')]"
流程名称 选择框: "xpath==//div[@class='el-row']//label[contains(text(),'流程名称')]/following-sibling::div//input"
流程名称 下拉选项: "xpath==//div[@x-placement='bottom-start']//li//span[contains(text(),'variable')]"
查询 按钮: "xpath==//form[@class='el-form form-item-less el-form--label-right']//button[1]//span[contains(text (), '查  询')]"
重置 按钮: "xpath==//form[@class='el-form form-item-less el-form--label-right']//button[2]//span[contains(text (), '重  置')]"
新增 按钮: "xpath==//*[@id='app']/div/div[2]/div[2]/section/div/div/div[2]/div[1]/button"
流程名称(Zh) 输入框: "xpath==//div[@class='el-table__body-wrapper is-scrolling-none']//table//tr[variable]//td[1]//input"
流程名称(En) 输入框: "xpath==//div[@class='el-table__body-wrapper is-scrolling-none']//table//tr[variable]//td[2]//input"
外部流程表单 下拉框: "xpath==//div[@class='el-table__body-wrapper is-scrolling-none']//table//tr[variable]//td[3]//input"
备注 输入框: "xpath==//div[@class='el-table__body-wrapper is-scrolling-none']//table//tr[variable]//td[4]//input"
保存 按钮: "xpath==//div[@class='el-table__fixed-body-wrapper']//table//tr[variable]//td[7]//button//span[contains(text (), '保存')]"
取消 按钮: "xpath==//div[@class='el-table__fixed-body-wrapper']//table//tr[variable]//td[7]//button//span[contains(text (), '取消')]"
编辑 按钮: "xpath==//div[@class='el-table__fixed-body-wrapper']//table//tr[variable]//td[7]//button//span[contains(text (), '编辑')]"
管理 按钮: "xpath==//div[@class='el-table__fixed-body-wrapper']//table//tr[variable]//td[7]//button//span[contains(text (), '管理')]"
节点配置 按钮: "xpath==//div[@class='el-table__fixed-body-wrapper']//table//tr[variable]//td[7]//button//span[contains(text (), '节点配置')]"
删除 按钮: "xpath==//div[@class='el-table__fixed-body-wrapper']//table//tr[variable]//td[7]//button//span[contains(text (), '删除')]"
删除 确认: "xpath==//*[@x-placement='bottom']/div[1]/div/button[2]"
获取列表数据数量 用于断言: "xpath==//span[@class='el-pagination__total']"

流程名称(Zh) 用于获取行号: "xpath==//div[@class='el-table__body-wrapper is-scrolling-none']//table//tr//td[1]"
列表断言: "xpath==//div[@class='el-table__body-wrapper is-scrolling-none']//table//tr[variable]//td[1]/div/div"

错误提示: "xpath==//p[contains(@class,'el-message__content')]"

关闭配置管理标签页: "xpath==//span[contains(text(),'配置管理')]//span[@class='el-icon-close']"
关闭节点配置标签页: "xpath==//span[contains(text(),'节点配置')]//span[@class='el-icon-close']"




