应用中心: "xpath==//span[text()='应用中心']"
#======================================================================应用====================================================================================
应用: "xpath==//div[text()='variable']"
操作按钮: 'xpath==//tr/td//div[contains(text(),"variable")]/../../../td[10]//span[contains(text(),"variabls")][1]'
