应用中心: "xpath==//span[text()='应用中心']"
#======================================================================应用====================================================================================
应用: "xpath==//div[text()='variable']"
操作按钮: 'xpath==//tr/td//div[contains(text(),"variable")]/../../../td[10]//span[contains(text(),"variable")][1]'

#======================================================================同意预约=======================================================================================
设置通知内容_发送通知: 'xpath==//body/div[2]//div[@role="dialog"]//span[text()="设置通知内容"]/../../div//span[text()=" 发送通知 "]'
设置通知内容_取消: 'xpath==//body/div[2]//div[@role="dialog"]//span[text()="设置通知内容"]/../../div//span[text()=" 取消 "]'

设置通知内容_收件人: 'xpath==//div/label[text()="收件人"]/..//input'
设置通知内容_抄送人: 'xpath==//div/label[text()="抄送人"]/..//input'
