一级菜单: "xpath==//ul[@class='menu-list']//span[contains(text(), 'variable')]"
二级菜单: "xpath==//ul[@role='menubar']//span[contains(text(), 'variable')]"
新增: "xpath==//div[@class='header']//span[contains(text(), '新增')]"
input输入框: "xpath==//label[contains(text(), 'variable')]/following-sibling::*//input"
textarea输入框: "xpath==//label[contains(text(), 'variable')]/following-sibling::*//textarea"
图片上传: "xpath==//label[@for='variable']/following-sibling::*//input"
#图标：icon
#封面：cover
新增对话框按钮: "xpath==//*[@at_my-file_add-dialog_variable]"
#确认：confirm
#取消：cancel
弹框X: "xpath==//div[@aria-label='variable']//button[@aria-label='Close']"
应用Item: "xpath==//div[@class='card-item']//span[contains(text(), 'variable')]"
应用Item more: "xpath==//span[contains(text(), 'variable')]/parent::*/following-sibling::*//i"
应用操作: "xpath==//ul[@x-placement='bottom-end']//li[contains(text(), 'variable')]"
删除确认: "xpath==//*[@aria-label='提示']//button[2]"
图标列表切换按钮: "xpath==//*[@xpath='at_my-file_tr-view']"
漏斗: "xpath==//div[@class='operator-list']//div[@class='tr-svg-icon']"
条件查询输入框: "xpath==//div[@class='filter-box']//label[contains(text(), 'variable')]/following-sibling::*//input"
状态选择: "xpath==//div[@class='el-scrollbar']//li[variable]"
查询框按钮: "xpath==//div[@class='btn-box']//span[contains(text(), 'variable')]"
添加+:  "xpath==//div[@class='tool-bar']//i"
树结构: "xpath==//div[@role='tree']//span[contains(text(), 'variable')]"





