一级菜单: "xpath==//ul[@class='menu-list']//span[contains(text(), 'variable')]"
二级菜单: "xpath==//ul[@role='menubar']//span[contains(text(), 'variable')]"
空间: "xpath==//*[@at_my-file_tree]//div//span[contains(text(), 'variable')]"
组件新增: "xpath==//*[@at_my-file_add]"
新增组件: "xpath==//*[@at_my-file_add-comp]"
名称输入框: "xpath==//*[@at_my-file_add-dialog_name]"
新增输入框: "xpath==//*[@at_my-file_add-dialog_variable]"
组件Item: "xpath==//*[@xpath='at_my-comp_list_item'][1]"
组件Item more: "xpath==//*[@xpath='at_my-comp_list_item'][1]//*[@at_my-file_more]"
删除: "xpath==//*[@xpath='at_my-file_contextmenu_remove_variable']"
组件删除确认: "xpath==//*[@aria-label='提示']//button[2]"
发布: "xpath==//*[@xpath='at_my-file_public']"
确定: "xpath==//*[@aria-label='variable']//button[2]"
#发布组件
#发布应用
#人员列表
新增: "xpath==//div[@class='header']//span[contains(text(), '新增')]"
input输入框: "xpath==//label[contains(text(), 'variable')]/following-sibling::*//input"
textarea输入框: "xpath==//label[contains(text(), 'variable')]/following-sibling::*//textarea"
图片上传: "xpath==//label[@for='variable']/following-sibling::*//input"
#应用图标：icon
#应用封面：cover
#菜单icon: menuIcon
新增对话框按钮: "xpath==//*[@at_my-file_add-dialog_variable]"
#确认：confirm
#取消：cancel
弹框X: "xpath==//div[@aria-label='variable']//button[@aria-label='Close']"
应用Item: "xpath==//div[@class='card-item']//span[contains(text(), 'variable')]"
应用Item more: "xpath==//span[contains(text(), 'variable')]/parent::*/following-sibling::*//i"
应用操作: "xpath==//ul[@x-placement='bottom-end']//li[contains(text(), 'variable')]"
提示框确认: "xpath==//*[@aria-label='提示']//button[2]"
#删除弹框
#回退弹框
图标列表切换按钮: "xpath==//*[@xpath='at_my-file_tr-view']"
#1: 已发布
#2: 未发布
菜单添加+:  "xpath==//div[@class='tool-bar']//i"
角色添加+: "xpath==//i[@class='el-icon-plus icon']"
树结构: "xpath==//div[@role='tree']//span[contains(text(), 'variable')]"
菜单编辑输入框: "xpath==//div[@role='tree']//input"
编辑确认: "xpath==//div[@class='edit-tree-item']//div/button[1]"
角色删除: "xpath==//div[normalize-space(text())='variable']/following-sibling::*//i[@class='el-icon-delete button-icon']"
子菜单添加: "xpath==//div[@title='variable']/following-sibling::*//i[@class='el-icon-plus icon line-icon']"
菜单类型: "xpath==//div[@role='radiogroup']//label[variable]"
#1: 外部链接
#2: 组件
菜单配置按钮: "xpath==//div[@class='tool']//button[variable]"
#1: 提交
#2: 重置
组件选择hover: "xpath==//input[@readonly='readonly']"
组件选择: "xpath==//div[@class='el-cascader-panel']//span[contains(text(), 'variable')]"
组件版本选择: "xpath==//div[@class='el-cascader-panel']//div[2]//li[1]"
应用配置header按钮: "xpath==//div[@class='header']//span[contains(text(), 'variable')]"
#权限配置页面
角色树: "xpath==//div[@role='treeitem']//div[contains(text(), 'variable')]"
角色编辑输入框: "xpath==//div[@role='treeitem']//input"
角色tab切换: "xpath==//div[@role='tablist']//*[contains(text(), 'variable')]"
权限类型添加按钮: "xpath==//button//span[normalize-space(text())='variable']"
#成员管理
人员列表输入框: "xpath==//*[@aria-label='人员列表']//input"
选择人员:  "xpath==//*[@aria-label='人员列表']//div[normalize-space(text())='variable']"
人员弹框确认: "xpath==//*[@at_my-file_add-dialog_confirm]"
成员删除按钮: "xpath==//table//tr[1]/td[6]"
#权限管理
输入框选择: "xpath==//table//tr[1]/td[variable]//input"
#2: 应用选择
#3: 版本选择
操作按钮: "xpath==//table//tr[1]/td[4]//button[variable]"
#新增: 1: 保存; 2: 取消; 3: 删除
#编辑: 1:编辑; 2:删除
应用/版本选择: "xpath==//div[@class='el-scrollbar']//span[normalize-space(text())='variable']"






