关键字: "xpath==//span[contains(text(),'终审版报表')]"
产品任命: "xpath==//li//span[text()='产品任命']"
区域产品概述: "xpath==//li//span[normalize-space(text())='区域产品概述']"
查看: "xpath==/html/body/div[1]/div/div[2]/section/div/section/div[1]/div/div/div[4]/div[1]/div[5]/div[2]/table/tbody/tr[3]/td[12]/div/button[1]/span"
版本记录: "xpath==//div[contains(text(),'版本记录')]"

分发: "xpath==/html/body/div[1]/div/div[2]/section/div/section/div[1]/div/div/div[4]/div[1]/div[5]/div[2]/table/tbody/tr[3]/td[12]/div/button[2]/span"
新增: "xpath==//button//span[text()=' +新增 ']"
分发角色: "xpath==//label[contains(text(),'分发角色')]/..//input"
角色: "xpath==//div[text()=' variable ']"
分发人员: "xpath==//label[contains(text(),'分发人员')]/..//input"
分发人员-姓名: "xpath==//li//span[contains(text(),'variable')]"
确定: "xpath==//button[@class='el-button el-button--primary el-button--mini']//span[normalize-space(text())='确定']"
提交分发: "xpath==//button//span[normalize-space(text())='提交分发']"
分发确定: "xpath==//div[@class='dialog-footer']//button//span[normalize-space(text())='确 定']"
最后确定: "xpath==//span//button//span[normalize-space(text())='确 定']"